# Generated by Django 3.0.2 on 2020-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_logfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./static/img')),
                ('name', models.CharField(max_length=20)),
                ('introduce', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(upload_to='check/excel/', verbose_name='文件'),
        ),
    ]
