# Generated by Django 3.0.2 on 2020-04-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20200424_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
