# Generated by Django 3.0.2 on 2020-04-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_activity_missions_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': '关于我们', 'verbose_name_plural': '关于我们'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '组织生活', 'verbose_name_plural': '组织生活'},
        ),
        migrations.AlterModelOptions(
            name='missions',
            options={'verbose_name': '负责任务', 'verbose_name_plural': '负责任务'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '支委', 'verbose_name_plural': '支委'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '党建指导老师', 'verbose_name_plural': '党建指导老师'},
        ),
        migrations.AlterField(
            model_name='about_us',
            name='text',
            field=models.CharField(max_length=500, verbose_name='关于我们'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ImageField(upload_to='img,,verbose_name="组织生活照片"'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='introduce',
            field=models.CharField(max_length=100, verbose_name='组织生活介绍'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(upload_to='excel/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='dzb_name',
            field=models.CharField(max_length=20, verbose_name='支部名称'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission_name',
            field=models.CharField(max_length=100, verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='missions_principle',
            field=models.CharField(max_length=20, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(upload_to='stu_img', verbose_name='学生图片'),
        ),
        migrations.AlterField(
            model_name='students',
            name='major_in',
            field=models.CharField(max_length=30, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='students',
            name='position',
            field=models.CharField(max_length=20, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='党建指导老师图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='introduce',
            field=models.CharField(max_length=100, verbose_name='党建指导老师介绍'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='党建指导老师姓名'),
        ),
    ]
