# Generated by Django 3.0.2 on 2020-04-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_auto_20200428_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfile',
            options={'verbose_name': '查询系统文件', 'verbose_name_plural': '查询系统文件'},
        ),
    ]
