# Generated by Django 3.0.2 on 2020-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20200428_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadsfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloads/', verbose_name='文件')),
                ('file_name', models.CharField(default='文件名', max_length=50, verbose_name='文件名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '下载中心文件',
                'verbose_name_plural': '下载中心文件',
            },
        ),
    ]
