# Generated by Django 3.0.2 on 2020-05-26 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_auto_20200525_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='major_in',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='专业'),
            preserve_default=False,
        ),
    ]
