# Generated by Django 3.0.7 on 2020-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0011_assistant_major_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='logfile_name', max_length=50, verbose_name='留言者名字')),
                ('comments', models.CharField(max_length=500, verbose_name='邮箱/电话')),
            ],
            options={
                'verbose_name': '与我们联系',
                'verbose_name_plural': '与我们联系',
            },
        ),
    ]
