# Generated by Django 3.0.7 on 2020-06-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0012_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_us',
        ),
    ]
