# Generated by Django 3.0.7 on 2020-06-24 15:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0014_auto_20200624_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='党建分类', max_length=10, verbose_name='分类名')),
                ('detail', models.CharField(default='党建分类具体描述', max_length=100, verbose_name='详细描述')),
            ],
            options={
                'verbose_name': '信息公开分类',
                'verbose_name_plural': '信息公开分类',
            },
        ),
        migrations.CreateModel(
            name='notice_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=100, verbose_name='文章标题')),
                ('author', models.DateTimeField(default='学生第三支部支委', verbose_name='发布人')),
                ('date', models.DateTimeField(verbose_name='发布时间')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='发布内容')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.notice_Category')),
            ],
            options={
                'verbose_name': '信息公开',
                'verbose_name_plural': '信息公开',
            },
        ),
    ]
