# Generated by Django 3.0.7 on 2020-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0015_notice_article_notice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_article',
            name='author',
            field=models.CharField(default='学生第三支部支委', max_length=10, verbose_name='发布人'),
        ),
    ]
