# Generated by Django 3.0.7 on 2020-06-26 11:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0016_auto_20200624_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', max_length=100, verbose_name='部门名称')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详细介绍')),
            ],
            options={
                'verbose_name': '下属部门',
                'verbose_name_plural': '下属部门',
            },
        ),
    ]
